### ISSUE TITLE
[Suggestion] Hosting images online.

### ISSUE THREAD

**Issue by piedcipher** [numerative/Posting-images-and-code-snippets-on-slack-best-practices#1]
First of all, it's a great idea. :+1: Repo should be shared frequently in the slack, I'll do that too. Now a suggestion, Instead of putting images in repo root, hosting them on imgur would ge a good idea. Repo would look clean.

**Comment by numerative** [comment]
Thanks for suggestion, @piedcipher . I've done that and it's already looking better! Thanks. :)
